# Generated by Django 4.0.6 on 2022-07-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('slug', models.SlugField(unique=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
