# Generated by Django 4.0.6 on 2022-07-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_link_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
